### PR TITLE
Dd 13

### PR DESCRIPTION
**Pull request by joshherkness**

### CODE REVIEW

**Comment by joshherkness** [comment]
Can you guys see if this is alright.  More internal changes to come, I just wanted to get something for you guys to see up there.

**Comment by jpherkness** [comment]
Looks good

**Review by jpherkness — APPROVED** [review]

**Comment by jpherkness** [comment]
Does this work on android?

**Comment by kdjohnson** [comment]
Looks good on iOS I'll test it out on android later today.

**Comment by kdjohnson** [comment]
This `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` needs to be added here `android/src/main/AndroidManifest.xml` below `<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>` but once you do that it works.

Here is how it looks.
screen shot 2017-04-12 at 12 55 14 pm

**Pull request merged**
