### PR TITLE
Remove report after 10 mins

### PR DESCRIPTION
**Pull request by kdjohnson**
Thoughts?

### CODE REVIEW

**Comment by jpherkness** [comment]
This looks good. It's probably fine for now, but we shouldn't have every client monitor all reports and remove those that are expired. But for this project, it's probably ok.

**Comment by kdjohnson** [comment]
Yea, this would work best on the server side.

**Comment by jpherkness** [comment]
If you want to do it client side, I recommend putting that code in the ReportService, and validating the reports before sending them to the components.

**Comment by kdjohnson** [comment]
@jpherkness  What do you think of that?

**Comment by jpherkness** [comment]
Looks good, the reports also need to be removed from the geofire ref.

**Comment by kdjohnson** [comment]
Cool. I'll add that in.

**Review by joshherkness — APPROVED** [review]
Looks decent.  Looks like Date.now() will be returned in UTC, so we have to make sure this will be displayed in the local timezone if we want to display the age of the report to the user.  The UTC should work well with the deleting a report, however, this might have unexpected results when more than one user is running the application.  I don't know how well firebase handles many items attempting to be removed at once.  My guess is that your console logs will be printing 'Remove report failed' all over the place when there are many carts and users using the application ate one time.  Should be fine for now though.

**Pull request merged**
